missyou:
  api-package: com.lin.missyou.api
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  profiles:
    active: dev
  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: none
=======
      ddl-auto: update
>>>>>>> 12fa53a0c91484d7b68238b939718dd6816248cf
